FROM eclipse-temurin:17-jre-jammy

RUN apt-get update -q && \
    apt-get install -y -q --no-install-recommends python3 python3-pip && \
    rm -rf /var/lib/apt/lists/* && \
    ln -sf /usr/bin/python3 /usr/bin/python

RUN pip3 install --no-cache-dir pyspark==3.5.3

ENV PYSPARK_SUBMIT_ARGS="--packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.3 pyspark-shell"

WORKDIR /app
CMD ["python3", "spark_processor.py"]
