# Generated by Django 6.0.5 on 2026-05-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='harbor_size',
            field=models.CharField(blank=True, db_index=True, default='', help_text='L=Large, M=Medium, S=Small, V=Very Small', max_length=1),
        ),
        migrations.AddIndex(
            model_name='port',
            index=models.Index(fields=['latitude', 'longitude'], name='port_latlon_idx'),
        ),
    ]
