# Generated by Django 6.0.5 on 2026-05-31 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_port_harbor_size_port_port_latlon_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmsi', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('ship_type', models.IntegerField(blank=True, null=True)),
                ('flag', models.CharField(blank=True, max_length=10)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('course', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_update'],
            },
        ),
        migrations.CreateModel(
            name='ShipPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.ship')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ship', '-timestamp'], name='core_shippo_ship_id_dad5d8_idx')],
            },
        ),
    ]
