# Generated by Django 6.0.5 on 2026-05-31 23:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ship_shipposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
