# Generated by Django 6.0.5 on 2026-05-31 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ship_last_update_manual'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ship',
            index=models.Index(fields=['latitude', 'longitude'], name='ship_latlon_idx'),
        ),
        migrations.AddIndex(
            model_name='ship',
            index=models.Index(fields=['last_update'], name='ship_update_idx'),
        ),
    ]
