apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: PostgreSQL
    type: postgres
    url: host.docker.internal:${DB_PORT:-5432}
    database: ${DB_NAME:-marine_traffic}
    user: ${DB_USER:-postgres}
    secureJsonData:
      password: ${DB_PASSWORD:-postgres}
    jsonData:
      sslmode: disable
      postgresVersion: 1500
    editable: true
